#configuracion de acceso a BD
spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update #create
#estrategia de generacion de base de datos
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/db_ws?useSSL=false 
    username: root
    password: root

server:
  port: 8090 